// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

final class ServerNativeProxyConfig extends ffi.Struct {
  external ffi.Pointer<ffi.Char> host;

  @ffi.Uint16()
  external int port;

  external ffi.Pointer<ffi.Char> backend_host;

  @ffi.Uint16()
  external int backend_port;

  @ffi.Uint8()
  external int backend_kind;

  external ffi.Pointer<ffi.Char> backend_path;

  @ffi.Uint32()
  external int backlog;

  @ffi.Uint8()
  external int v6_only;

  @ffi.Uint8()
  external int shared;

  @ffi.Uint8()
  external int request_client_certificate;

  @ffi.Uint8()
  external int http2;

  @ffi.Uint8()
  external int http3;

  external ffi.Pointer<ffi.Char> tls_cert_path;

  external ffi.Pointer<ffi.Char> tls_key_path;

  external ffi.Pointer<ffi.Char> tls_cert_password;

  @ffi.Uint8()
  external int benchmark_mode;

  external ffi.Pointer<ffi.Void> direct_request_callback;
}
