// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:server_native/src/zig_ffi.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int32 Function()>(symbol: 'server_native_zig_transport_version')
external int server_native_zig_transport_version();

@ffi.Native<
  ffi.Pointer<ffi.Void> Function(ffi.Pointer<ffi.Void>, ffi.Pointer<ffi.Uint16>)
>(symbol: 'server_native_zig_start_proxy_server')
external ffi.Pointer<ffi.Void> server_native_zig_start_proxy_server(
  ffi.Pointer<ffi.Void> config,
  ffi.Pointer<ffi.Uint16> out_port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_zig_begin_shutdown',
)
external void server_native_zig_begin_shutdown(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_zig_shutdown_done',
)
external bool server_native_zig_shutdown_done(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Int64)>(
  symbol: 'server_native_zig_set_event_port',
)
external void server_native_zig_set_event_port(
  ffi.Pointer<ffi.Void> handle,
  int port,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_zig_stop_proxy_server',
)
external void server_native_zig_stop_proxy_server(ffi.Pointer<ffi.Void> handle);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Pointer<ffi.Void>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>(symbol: 'server_native_zig_push_direct_response_frame')
external int server_native_zig_push_direct_response_frame(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  ffi.Pointer<ffi.Uint8> response_payload,
  int response_payload_len,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Pointer<ffi.Void>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>(symbol: 'server_native_zig_try_push_response')
external int server_native_zig_try_push_response(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  ffi.Pointer<ffi.Uint8> payload,
  int length,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>, ffi.Uint64, ffi.UintPtr)>(
  symbol: 'server_native_zig_consume_request',
)
external void server_native_zig_consume_request(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  int count,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Pointer<ffi.Void>,
    ffi.Uint64,
    ffi.Pointer<ffi.Uint8>,
    ffi.Uint64,
  )
>(symbol: 'server_native_zig_complete_direct_request')
external int server_native_zig_complete_direct_request(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  ffi.Pointer<ffi.Uint8> response_payload,
  int response_payload_len,
);

@ffi.Native<
  ffi.Uint8 Function(
    ffi.Pointer<ffi.Void>,
    ffi.Uint32,
    ffi.Pointer<ffi.Uint64>,
    ffi.Pointer<ffi.Pointer<ffi.Uint8>>,
    ffi.Pointer<ffi.Uint64>,
  )
>(symbol: 'server_native_zig_poll_direct_request_frame')
external int server_native_zig_poll_direct_request_frame(
  ffi.Pointer<ffi.Void> handle,
  int timeout_millis,
  ffi.Pointer<ffi.Uint64> out_request_id,
  ffi.Pointer<ffi.Pointer<ffi.Uint8>> out_payload,
  ffi.Pointer<ffi.Uint64> out_payload_len,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Uint8>, ffi.Uint64)>(
  symbol: 'server_native_zig_free_direct_request_payload',
)
external void server_native_zig_free_direct_request_payload(
  ffi.Pointer<ffi.Uint8> payload,
  int payload_len,
);

@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_dart_api_initialize',
)
external int server_native_dart_api_initialize(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>(
  symbol: 'server_native_dart_post_integer',
)
external bool server_native_dart_post_integer(int port_id, int value);

@ffi.Native<ffi.Pointer<ffi.Void> Function(ffi.UintPtr)>(
  symbol: 'server_native_zig_queue_create',
)
external ffi.Pointer<ffi.Void> server_native_zig_queue_create(
  int slot_capacity,
);

@ffi.Native<ffi.Void Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_zig_queue_destroy',
)
external void server_native_zig_queue_destroy(ffi.Pointer<ffi.Void> handle);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Void>,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
  )
>(symbol: 'server_native_zig_queue_push')
external bool server_native_zig_queue_push(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  ffi.Pointer<ffi.Uint8> payload,
  int payload_len,
);

@ffi.Native<
  ffi.Bool Function(
    ffi.Pointer<ffi.Void>,
    ffi.Int64,
    ffi.Pointer<ffi.Uint8>,
    ffi.UintPtr,
  )
>(symbol: 'server_native_zig_queue_push_request_start')
external bool server_native_zig_queue_push_request_start(
  ffi.Pointer<ffi.Void> handle,
  int request_id,
  ffi.Pointer<ffi.Uint8> descriptor,
  int descriptor_len,
);

@ffi.Native<ffi.UintPtr Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_zig_queue_length',
)
external int server_native_zig_queue_length(ffi.Pointer<ffi.Void> handle);

@ffi.Native<ffi.Bool Function(ffi.Pointer<ffi.Void>, ffi.Int64)>(
  symbol: 'server_native_zig_queue_post_next',
)
external bool server_native_zig_queue_post_next(
  ffi.Pointer<ffi.Void> handle,
  int port_id,
);
