// ignore_for_file: type=lint
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:native_toolchain_zig`.
@ffi.DefaultAsset('package:server_native/src/zig_ffi.g.dart')
library;

import 'dart:ffi' as ffi;

@ffi.Native<ffi.Int32 Function()>(
  symbol: 'server_native_transport_version',
)
external int server_native_transport_version();

@ffi.Native<ffi.IntPtr Function(ffi.Pointer<ffi.Void>)>(
  symbol: 'server_native_dart_api_initialize',
)
external int server_native_dart_api_initialize(ffi.Pointer<ffi.Void> data);

@ffi.Native<ffi.Bool Function(ffi.Int64, ffi.Int64)>(
  symbol: 'server_native_dart_post_integer',
)
external bool server_native_dart_post_integer(int port_id, int value);
