import 'dart:io';

const _pubspecVersionPattern = r'^version:\s*([^\s]+)\s*$';
const _prebuiltTagPrefix = 'server-native-prebuilt-v';

Future<void> main() async {
  final packageRoot = Directory.current;
  final pubspecFile = File('${packageRoot.path}/pubspec.yaml');
  if (!pubspecFile.existsSync()) {
    stderr.writeln('Missing pubspec.yaml at ${pubspecFile.path}');
    exitCode = 1;
    return;
  }

  final pubspec = await pubspecFile.readAsString();
  final match = RegExp(
    _pubspecVersionPattern,
    multiLine: true,
  ).firstMatch(pubspec);
  if (match == null) {
    stderr.writeln('Unable to parse package version from pubspec.yaml');
    exitCode = 1;
    return;
  }

  final version = match.group(1)!;
  final prebuiltTag = '$_prebuiltTagPrefix$version';
  final outputFile = File(
    '${packageRoot.path}/lib/src/generated/prebuilt_release.g.dart',
  );
  outputFile.parent.createSync(recursive: true);
  await outputFile.writeAsString(
    _render(version: version, prebuiltTag: prebuiltTag),
  );
  stdout.writeln('Generated ${outputFile.path}');
}

String _render({required String version, required String prebuiltTag}) {
  return '''
// GENERATED CODE - DO NOT MODIFY BY HAND.
// Generated by `dart run tool/generate_prebuilt_release.dart`.

/// Current Dart package version used for release metadata.
const String serverNativePackageVersion = '$version';

/// Default prebuilt binary release tag expected by this package version.
const String serverNativePrebuiltReleaseTag = '$prebuiltTag';
''';
}
